### ISSUE TITLE
qemu-broker Serialization macd_generated.h flatbuffers version error when compile qemu plugin

### ISSUE THREAD

**Issue by pengking** [securesystemslab/LLVM-MCA-Daemon#10]
I use the latest flatbuffers include to compile qemu plugin, it will result compile failed, these failed may be relate to flatbuffers version.  I use flatbuffers latest version which commit id 7106d86685e3395efc6df5d2ee5914fe622ed6b9

**Comment by chinmaydd** [comment]
Hi @pengking, thanks for your interest. I have not experimented with the latest `flatbuffers` version. 

Could you share what the compilation error is ? Thanks !

**Comment by chinmaydd** [comment]
Closing due to no response. The QEMU plugin available on the `main` branch reliably compiles (per the instructions mentioned in the README). Please reopen if you continue to see failures.

Thanks !
